#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./scripts/summarize_dynamic_mesh.sh <path/to/dynamic_mesh_*.log>
#
# Example:
#   ./scripts/summarize_dynamic_mesh.sh results/dynamic_mesh_20260506_225100.log

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <dynamic_mesh_log_file>"
  exit 1
fi

LOG_FILE="$1"

if [[ ! -f "${LOG_FILE}" ]]; then
  echo "ERROR: File not found: ${LOG_FILE}"
  exit 1
fi

awk '
BEGIN {
  round = 0
  section = "none"
  tcp_retr_total = 0
  jitter_count = 0
}

function trim(s) {
  gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "", s)
  return s
}

function safe_num(v) {
  if (v == "" || v ~ /[^0-9.\-]/) return "NA"
  return v + 0
}

/=== ROUND [0-9]+\/[0-9]+: DISCONNECT/ {
  match($0, /ROUND [0-9]+/)
  round = substr($0, RSTART + 6, RLENGTH - 6) + 0
  section = "disconnect"
  next
}

/=== ROUND [0-9]+\/[0-9]+: RECONNECT/ {
  match($0, /ROUND [0-9]+/)
  round = substr($0, RSTART + 6, RLENGTH - 6) + 0
  section = "reconnect"
  next
}

/Ping during disconnect/ { section = "ping_disconnect"; next }
/Ping after reconnect/   { section = "ping_reconnect"; next }
/Throughput during disconnect/ { section = "iperf_disconnect"; next }
/Throughput after reconnect/   { section = "iperf_reconnect"; next }

# ping summary sample:
# "3 packets transmitted, 3 received, 0% packet loss, time 2002ms"
/packets transmitted/ {
  if (round <= 0) next
  line = $0
  # Packet loss percentage is always before "% packet loss"
  split(line, parts, "% packet loss")
  split(parts[1], left, ",")
  loss_str = trim(left[length(left)])
  gsub(/[^0-9.]/, "", loss_str)
  loss = (loss_str == "" ? "NA" : loss_str + 0)

  if (section == "ping_disconnect") {
    loss_disconnect[round] = loss
  } else if (section == "ping_reconnect") {
    loss_reconnect[round] = loss
  }
  next
}

# iperf3 TCP sender summary sample:
# "[  5]   0.00-5.00   sec   565 MBytes   948 Mbits/sec   22             sender"
/sender$/ && /bits\/sec/ {
  if (round <= 0) next
  line = $0
  gsub(/\[/, " [", line)
  n = split(line, fields, /[[:space:]]+/)

  # Look for throughput number followed by K/M/Gbits/sec
  t_value = ""
  t_unit = ""
  retr = ""
  for (i = 1; i <= n; i++) {
    if (fields[i] ~ /bits\/sec$/ && i > 1) {
      t_value = fields[i-1]
      t_unit = fields[i]
      # retries often right before sender token
      for (j = i + 1; j <= n; j++) {
        if (fields[j] == "sender" && j > i + 0) {
          retr = fields[j-1]
          break
        }
      }
      break
    }
  }

  if (t_value == "" || t_unit == "") next
  mbps = t_value + 0
  if (t_unit ~ /^Kbits\/sec$/) mbps = mbps / 1000.0
  else if (t_unit ~ /^Gbits\/sec$/) mbps = mbps * 1000.0
  else if (t_unit ~ /^bits\/sec$/) mbps = mbps / 1000000.0

  if (section == "iperf_disconnect") {
    thr_disconnect[round] = mbps
    if (retr ~ /^[0-9]+$/) retr_disconnect[round] = retr + 0
  } else if (section == "iperf_reconnect") {
    thr_reconnect[round] = mbps
    if (retr ~ /^[0-9]+$/) retr_reconnect[round] = retr + 0
  } else if (section == "none" || section == "baseline") {
    baseline_thr = mbps
  }
  next
}

# iperf3 UDP summary (optional if user runs -u):
# "... sec ... Mbits/sec  0.123 ms  0/1000 (0%)  receiver"
/receiver$/ && /bits\/sec/ && /ms/ && /\([0-9.]+%\)/ {
  # not required for current script flow, but keep hook for future extension
  next
}

END {
  rounds = 0
  for (r in loss_disconnect) if (r > rounds) rounds = r
  for (r in loss_reconnect) if (r > rounds) rounds = r
  for (r in thr_disconnect) if (r > rounds) rounds = r
  for (r in thr_reconnect) if (r > rounds) rounds = r

  print "===== Dynamic Mesh KPI Summary ====="
  print "log_file: " FILENAME
  if (baseline_thr != "") {
    printf("baseline_throughput_mbps: %.2f\n", baseline_thr)
  } else {
    print "baseline_throughput_mbps: NA"
  }
  print ""

  if (rounds == 0) {
    print "No round data found. Make sure this log was generated by dynamic_mesh_test.sh."
    exit 0
  }

  print "round,loss_disconnect_pct,loss_reconnect_pct,thr_disconnect_mbps,thr_reconnect_mbps,thr_recovery_pct,retrans_disconnect,retrans_reconnect"

  sum_loss_d = 0; cnt_loss_d = 0
  sum_loss_r = 0; cnt_loss_r = 0
  sum_thr_d = 0; cnt_thr_d = 0
  sum_thr_r = 0; cnt_thr_r = 0
  recovery_bad = 0

  for (i = 1; i <= rounds; i++) {
    ld = (i in loss_disconnect ? loss_disconnect[i] : "NA")
    lr = (i in loss_reconnect ? loss_reconnect[i] : "NA")
    td = (i in thr_disconnect ? thr_disconnect[i] : "NA")
    tr = (i in thr_reconnect ? thr_reconnect[i] : "NA")
    rd = (i in retr_disconnect ? retr_disconnect[i] : "NA")
    rr = (i in retr_reconnect ? retr_reconnect[i] : "NA")

    rec = "NA"
    if (td != "NA" && tr != "NA" && td > 0) {
      rec = (tr / td) * 100.0
    } else if (baseline_thr != "" && tr != "NA" && baseline_thr > 0) {
      rec = (tr / baseline_thr) * 100.0
    }

    if (ld != "NA") { sum_loss_d += ld; cnt_loss_d++ }
    if (lr != "NA") { sum_loss_r += lr; cnt_loss_r++ }
    if (td != "NA") { sum_thr_d += td; cnt_thr_d++ }
    if (tr != "NA") { sum_thr_r += tr; cnt_thr_r++ }
    if (rec != "NA" && rec < 80) recovery_bad++

    if (td == "NA") td_out = "NA"; else td_out = sprintf("%.2f", td)
    if (tr == "NA") tr_out = "NA"; else tr_out = sprintf("%.2f", tr)
    if (rec == "NA") rec_out = "NA"; else rec_out = sprintf("%.1f", rec)

    print i "," ld "," lr "," td_out "," tr_out "," rec_out "," rd "," rr
  }

  print ""
  print "----- Aggregate KPIs -----"
  if (cnt_loss_d > 0) printf("avg_loss_disconnect_pct: %.2f\n", sum_loss_d / cnt_loss_d); else print "avg_loss_disconnect_pct: NA"
  if (cnt_loss_r > 0) printf("avg_loss_reconnect_pct: %.2f\n", sum_loss_r / cnt_loss_r); else print "avg_loss_reconnect_pct: NA"
  if (cnt_thr_d > 0) printf("avg_thr_disconnect_mbps: %.2f\n", sum_thr_d / cnt_thr_d); else print "avg_thr_disconnect_mbps: NA"
  if (cnt_thr_r > 0) printf("avg_thr_reconnect_mbps: %.2f\n", sum_thr_r / cnt_thr_r); else print "avg_thr_reconnect_mbps: NA"
  printf("rounds_below_80pct_recovery: %d/%d\n", recovery_bad, rounds)
}
' "${LOG_FILE}"
